# Generated by Django 5.2.2 on 2025-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_total_sum_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='clients_used',
            field=models.ManyToManyField(blank=True, related_name='used_promocodes', to='main.client'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
