# Generated by Django 5.2.2 on 2025-06-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_promocode_clients_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
    ]
